format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = '[❮ \[vim\]](purple)'

[directory]
truncate_to_repo = false
truncation_length = 99
truncation_symbol = '…/'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]

[git_state]

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
